### ISSUE TITLE
 Last Execution Date for Metrics Execution is Thu Jan 01 00:00:00 UTC 1970

### ISSUE THREAD

**Issue by valeriocos** [crossminer/scava#134]
Some projects seem to have a wrong last execution date (1970-01-01), for instance the Epsilon and Sirius projects in castalia (click on http://ci4.castalia.camp:5601/project/configure/modeling.sirius and then on the link under `Execution Metrics`). I see the same problem in my local env.

These projects are not imported to Kibana since they miss the execution date information (which is needed to plot the metrics on time axis).

@ambpro do you experience the same problem?

**Comment by valeriocos** [comment]
![captura de pantalla de 2019-03-08 17-12-46](https://user-images.githubusercontent.com/6515067/54040525-e3ef8a00-41c5-11e9-8a90-ee7883abc2e5.png)

**Comment by ambpro** [comment]
@valeriocos , I pushed tow fixes related to this issue. Could you please test it on your side ?

**Comment by valeriocos** [comment]
sure! thank you @ambpro

**Comment by creat89** [comment]
I've been working with @mhow2, and we're having a similar issue. But in this case, the metrics that have the old date are those that have not been executed.

This is the log, and you can see that only two metrics have been executed:
```
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:17): Extracting Factoid metrics of all metricProviders
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:17): Extracting Factoid metricProviders is done.
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:17): Creating metric branches.
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:17): Creating metric branches is done in 0 ms
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:17): Dates: 3
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:17): Project TestAdrianTask execution ( TestAdrian:Testing : Date 20190211 )
INFO  [AnalysisSchedulingService] (15:35:17): Starting new daily execution AnalysisTask 'TestAdrian:Testing'
INFO  [AnalysisSchedulingService] (15:35:17): Starting new daily execution AnalysisTask 'TestAdrian:Testing' is done.
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:17): Date: 20190211, project: TestAdrian
INFO  [ProjectDelta (TestAdrian,20190211)] (15:35:17): Creating Delta
INFO  [ProjectDelta (TestAdrian,20190211)] (15:35:28): Created Delta (11217 ms)
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Starting execution AnalysisTask 'TestAdrian:Testing' with MetricExecution 'org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider'
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Adding dependencies to metricProvider 'org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider' into project 'TestAdrian'
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Added dependencies to metricProvider 'org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider' into project 'TestAdrian'
INFO  [AnalysisSchedulingService] (15:35:28): Starting MetricExecution 'org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider'
INFO  [AnalysisSchedulingService] (15:35:28): Update the worker 'w2' heartBeat Tue Mar 26 15:35:28 UTC 2019'
INFO  [AnalysisSchedulingService] (15:35:28): Starting MetricExecution 'org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider' is done.
INFO  [AnalysisSchedulingService] (15:35:28): Starting find out MetricExecution 'org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider' on Project 'TestAdrian'
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Starting Metric Execution (plaintextprocessing).
INFO  [AnalysisSchedulingService] (15:35:28): Ending MetricExecution 'org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider'
INFO  [AnalysisSchedulingService] (15:35:28): Ending MetricExecution 'org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider' is done.
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Ending execution AnalysisTask 'TestAdrian:Testing' with MetricExecution 'org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider' done in 23 ms
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:28): Executing factoids.
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Starting execution AnalysisTask 'TestAdrian:Testing' with MetricExecution 'org.eclipse.scava.factoid.bugs.emotion.BugsChannelEmotionFactoid'
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Adding dependencies to metricProvider 'org.eclipse.scava.factoid.bugs.emotion.BugsChannelEmotionFactoid' into project 'TestAdrian'
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Added dependencies to metricProvider 'org.eclipse.scava.factoid.bugs.emotion.BugsChannelEmotionFactoid' into project 'TestAdrian'
INFO  [AnalysisSchedulingService] (15:35:28): Starting MetricExecution 'org.eclipse.scava.factoid.bugs.emotion.BugsChannelEmotionFactoid'
INFO  [AnalysisSchedulingService] (15:35:28): Update the worker 'w2' heartBeat Tue Mar 26 15:35:28 UTC 2019'
INFO  [AnalysisSchedulingService] (15:35:28): Starting MetricExecution 'org.eclipse.scava.factoid.bugs.emotion.BugsChannelEmotionFactoid' is done.
INFO  [AnalysisSchedulingService] (15:35:28): Starting find out MetricExecution 'org.eclipse.scava.factoid.bugs.emotion.BugsChannelEmotionFactoid' on Project 'TestAdrian'
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Starting Metric Execution (BugChannelEmotion).
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Started Metric Executed (BugChannelEmotion).
INFO  [AnalysisSchedulingService] (15:35:28): Ending MetricExecution 'org.eclipse.scava.factoid.bugs.emotion.BugsChannelEmotionFactoid'
INFO  [AnalysisSchedulingService] (15:35:28): Ending MetricExecution 'org.eclipse.scava.factoid.bugs.emotion.BugsChannelEmotionFactoid' isdone.
INFO  [MetricListExecutor (TestAdrian, 20190211)] (15:35:28): Ending execution AnalysisTask 'TestAdrian:Testing' with MetricExecution 'org.eclipse.scava.factoid.bugs.emotion.BugsChannelEmotionFactoid' done in 11 ms
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:28): Updating last executed date.
INFO  [ProjectExecutor (w2:TestAdrian:Testing)] (15:35:28): Date 20190211 Task Execution ( TestAdrian:Testing completed in 11254 ms )
```
These correspond to those that have the date of 2019:
![image](https://user-images.githubusercontent.com/17121539/55011377-b5531b00-4fdd-11e9-9d30-3f3f62a496c4.png)

I'm guessing that this issue is somehow related to issue https://github.com/crossminer/scava/issues/116. In which the project analyzer is not finding all the metrics.

**Comment by valeriocos** [comment]
sorry @ambpro @creat89 I'm a bit late on testing it

**Comment by valeriocos** [comment]
Hi @ambpro sorry for the late feedback. I still see projects without execution date information (e.g., netty and activemq). I restarted the analysis for netty yesterday evening, the analysis is still in progress (but the progress bar is still empty)[1]. I have also tried to add a new project, but when saving the anaylsis task, the start date is removed and the task is not created [2]. 

Let me know if I'm missing something (I'm using the docker-compose-build in scava-deployment).
Thanks

[1]  
![Captura de pantalla de 2019-03-30 15-28-18](https://user-images.githubusercontent.com/6515067/55277507-52c18e00-5301-11e9-8e7a-4eb4387b34b7.png)

[2] 
![scava-test](https://user-images.githubusercontent.com/6515067/55277864-0d06c480-5305-11e9-9e61-44fcbd1fb73f.gif)

**Comment by valeriocos** [comment]
For [2], I did a `docker system prune -a` and then followed the instructions at [scava-deployment](https://github.com/crossminer/scava-deployment/tree/dev#scava-deployment). Now the task is correctly added, the list of metrics is partially updated as reported by @creat89 

At the time of testing, the scava version is the last one: https://github.com/crossminer/scava/commit/c560b2722fc0caf1af86712e2534a78b5be69108

**Comment by ambpro** [comment]
Hello @valeriocos, do you have any updates about the current issue?
Thanks

**Comment by valeriocos** [comment]
Everything seems fine @ambpro , thank you for the heads-up
